using UnityEngine;
using System.Collections.Generic;
using System.Linq;

public class Territory : MonoBehaviour
{
    [Header("Settings")]
    public string territoryName;
    public TerritoryType type;
    public CharacterData leader;

    [Header("Hierarchy")]
    public Territory parentTerritory; // The County this Town belongs to
    public List<Territory> subTerritories = new List<Territory>(); // The Towns in this County

    private SpriteRenderer spriteRenderer;

    public int population;    // Population of this territory

    // Inside Territory.cs
    public SettlementSize size;
    public bool isCapital = false;

    public GameObject capitalIcon;

    [Header("Feudal Economy")]
    public float localWealth; // Wealth generated by this territory
    public float personalTreasury; 
    public float taxRateToLord = 0.2f; // 20% goes to the person above them
    //public DevelopmentFocus currentFocus = DevelopmentFocus.Balanced;

    [Header("Buildings")]
    public List<BuildingData> currentBuildings = new List<BuildingData>();
    public float instability = 0; // Instability level of this territory

    public Kingdom ownerKingdom; // The Kingdom that owns this territory

    public Color territoryColour;

    void Awake()
    {
        spriteRenderer = GetComponent<SpriteRenderer>();
    }

    // Call this when a war ends or land is traded
    public void ChangeOwner(CharacterData newLeader)
    {
        leader = newLeader;

        Debug.Log($"{territoryName} is now ruled by {newLeader.characterName}");
    }

    public void RefreshUI()
    {
        if (capitalIcon != null)
        {
            capitalIcon.SetActive(isCapital);

            // Optional: Scale the icon based on how big the settlement is
            if (isCapital)
            {
                float scale = size switch
                {
                    SettlementSize.BigVillage => 0.2f,
                    SettlementSize.SmallTown => 0.3f,
                    SettlementSize.MarketTown => 0.4f,
                    SettlementSize.Borough => 0.5f,
                    SettlementSize.BigTown => 0.65f,
                    SettlementSize.SmallCity => 0.8f,
                    SettlementSize.City => 0.95f,
                    _ => 0.0f,
                };
                capitalIcon.transform.localScale = new Vector3(scale, scale, 1f);
            }
        }
    }

    public void CalculatePopulation()
    {
        if (subTerritories.Count > 0)
        {
            population = 0;
            foreach (var sub in subTerritories) population += sub.population;
        }
    }

    public int GetBuildingLevel(string buildingName)
    {
        foreach (BuildingData b in currentBuildings)
        {
            if (b.buildingName == buildingName)
            {
                return b.level;
            }
        }
        return 0; // Not built
    }

    public bool HasBuilding(string nameToCheck)
    {
        // 1. Check this specific territory's list
        if (currentBuildings.Any(b => b.buildingName == nameToCheck))
            return true;

        // 2. Check sub-territories (counties inside a province)
        foreach (Territory sub in subTerritories)
        {
            if (sub.currentBuildings.Any(b => b.buildingName == nameToCheck))
                return true;
        }

        return false;
    }

    public float GetGoldPerTurn() // Changed to float to prevent rounding errors
{
    if (this.type == TerritoryType.Town)
    {
        float total = 0;
        foreach (var b in currentBuildings)
        {
            total += b.GetGoldPerTurn();
        }
        // Add the population tax here too so it's included in the "Town's output"
        total += population / 100f;
        localWealth = total; 
        return total;
    }

    // For Counties, Provinces, and Kingdoms, we just return the stored sum
    return localWealth;
}
}

public enum SettlementSize { Hamlet, Village, BigVillage, SmallTown, MarketTown, Borough, BigTown, SmallCity, City }