using UnityEngine;
using System.Collections.Generic;

public class Territory : MonoBehaviour
{
    [Header("Settings")]
    public string territoryName;
    public TerritoryType type;
    public CharacterData leader;

    [Header("Hierarchy")]
    public Territory parentTerritory; // The County this Town belongs to
    public List<Territory> subTerritories = new List<Territory>(); // The Towns in this County

    private SpriteRenderer spriteRenderer;

    // Inside Territory.cs
    public SettlementSize size;
    public bool isCapital = false;

    public GameObject capitalIcon;

    public List<BuildingData> currentBuildings = new List<BuildingData>();
    public float localWealth; // Wealth generated by this territory
    public int population;    // Population of this territory
    public float instability = 0; // Instability level of this territory

    public Kingdom ownerKingdom; // The Kingdom that owns this territory

    void Awake()
    {
        spriteRenderer = GetComponent<SpriteRenderer>();
    }

    // Call this when a war ends or land is traded
    public void ChangeOwner(CharacterData newLeader)
    {
        leader = newLeader;
        // Update the visual color to match the leader's faction color
        // For now, let's just use a random color or a placeholder
        spriteRenderer.color = newLeader.factionColor;

        Debug.Log($"{territoryName} is now ruled by {newLeader.characterName}");
    }

    public void RefreshUI()
    {
        if (capitalIcon != null)
        {
            capitalIcon.SetActive(isCapital);

            // Optional: Scale the icon based on how big the settlement is
            if (isCapital)
            {
                float scale = size switch
                {
                    SettlementSize.BigVillage => 0.2f,
                    SettlementSize.SmallTown => 0.3f,
                    SettlementSize.MarketTown => 0.4f,
                    SettlementSize.Borough => 0.5f,
                    SettlementSize.BigTown => 0.65f,
                    SettlementSize.SmallCity => 0.8f,
                    SettlementSize.City => 0.95f,
                    _ => 0.0f,
                };
                capitalIcon.transform.localScale = new Vector3(scale, scale, 1f);
            }
        }
    }

    public void CalculatePopulation()
    {
        population = 0;
        foreach (Territory sub in subTerritories)
        {
            population += sub.population;
        }
    }

    public int GetBuildingLevel(string buildingName)
    {
        foreach (BuildingData b in currentBuildings)
        {
            if (b.buildingName == buildingName)
            {
                return b.level;
            }
        }
        return 0; // Not built
    }
}

public enum SettlementSize { Hamlet, Village, BigVillage, SmallTown, MarketTown, Borough, BigTown, SmallCity, City }